---

- name: Ensure Perl Dependencies is installed
  yum:  name={{item}} state=present
  with_items:
    - gcc
    - perl-CPAN

- name: Test for cpanm
  shell: perl -MApp::cpanminus -e1
  register: perl_cpanm_result
  ignore_errors: true

# - name:  Get cpanm
#   get_url: url=http://cpanmin.us dest=/tmp/

# - name: Get CPANM
    
- name:  Install CPANm
  shell: curl -L http://cpanmin.us | perl - App::cpanminus
  when:  perl_cpanm_result|failed

- name: Create symbolik link for CPANm
  file:
    src: /usr/local/bin/cpanm
    dest: /usr/bin/cpanm
    state: link

- name: Install CPAN Module for Linux
  cpanm: name=Sys::Statistics::Linux

